[package]
name = "aoc22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eval = "0.4.3"
grid = "0.9.0"
itertools = "0.10.5"
json = "0.12.4"
regex = "1.7.0"
sscanf = "0.4.0"
text_io = "0.1.12"
